is_debug: true
listen:
  port: 8080
cors:
  allowed_origins: filmium.ru
storage:
  # password from env
  user:     postgres
  dbname:   postgres
  host:     postgres
  port:     5432
  sslmode:  disable
  search_path: filmium
redis:
  user:     user
  host:     redis
  port:     6379
  dbnum:    0
logging:
  dir: log
  filename: all.log.json

