is_debug: true
server:
  port: 8080
  # seconds
  read_timeout: 10
  write_timeout: 10
  read_header_timeout: 5
  shutdown_timeout: 5
service_sesion:
  addr: 172.27.195.147:8081
service_user:
  addr: 172.27.195.147:8082
csrf:
  header: csrf-token
  # seconds
  expires_at: 7200
cors:
  allowed_origins: filmium.ru
avatar:
  name_form_file: avatar
  # mb
  max_size_body: 10
postgres:
  # password from env
  user:     postgres
  dbname:   postgres
  host:     postgres
  port:     5432
  sslmode:  disable
  search_path: filmium
redis:
  user:     user
  host:     redis
  port:     6379
  dbnum:    0
content:
  host: content
  port: 8081
logging:
  dir: log
  filename: all.log.json
  level: 
    - all

