is_debug: true
listen:
  port: 8080
cors:
  allowed_origins: filmium.ru
storage:
  # password from env
  user:     postgres
  dbname:   postgres
  host:     127.0.0.1
  port:     5432
  sslmode:  disable
  search_path: filmium
redis:
  user:     user
  host:     localhost
  port:     6379
  dbnum:    0

