version: '3'

# для того, чтобы скрипт инициализации отработал, БД должна быть пуста
  # 1. sudo rm -rf tmp_persist/pgdata/*
  # 2. sudo -i && rm -rf tmp_persist/pgdata/*

# docker compose up --build 
  # если произошли изменения в Dockerfile
  # или есть скрипт заполнения бд, скачиваемый по ссылке, изменился

# docker compose config - подставляет переменные окружения из .env в ${POSTGRES_PASSWORD} и показывает итоговый конфиг 

services:
  # зайти в контейнере в бд "psql -U postgres"
  postgres:
    build: .
    restart: always
    environment: 
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5431:5432'
    volumes:
      # локальная директория для хранения данных бд
      - ./tmp_persist:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    links:
        - "postgres:postgres"
    ports:
      - 8090:8080
  redis:
    image: 'redis'
    volumes:
      - ./tmp_persist/redis_data:/data
    ports:
      - '6379:6379'
