version: '3'


services:

# -------------------------------------
# ===========[ STORAGES ]==============
# -------------------------------------
  postgres:
    build:
      context: .
      dockerfile: postgres-dockerfile
    restart: always
    environment: 
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}  # from .env
    ports:
      - 5431:5432
    logging:
      options:
        max-size: 10m
        max-file: "3"
    command:
      - "postgres"
      - "-c"
      - "log_statement=all"
      - "-c"
      - 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./config/postgres:/etc/postgresql
      - ./log/postgres:/var/lib/postgresql/data/log
    networks:
      net:
        ipv4_address: 192.168.243.20
        
# -------------------------------------

  redis:
    image: 'redis'
    restart: always
    volumes:
      - redis-data:/data
    networks:
      net:
        ipv4_address: 192.168.243.21
      
# -------------------------------------
# ==========[ SERVICES ]===============
# -------------------------------------

  content:
    build:
      context: .
      dockerfile: services-dockerfile
    restart: always
    links:
      - postgres:postgres
    depends_on:
      - postgres
    environment: 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_CONTENT}
    volumes:
    - ./build/content:/build/
    - ./log:/log
    networks:
      net:
        ipv4_address: 192.168.243.11


# -------------------------------------

  user:
    build:
      context: .
      dockerfile: services-dockerfile
    restart: always
    links:
      - postgres:postgres
    depends_on:
      - postgres
    environment: 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_USER}
    volumes:
    - ./build/user:/build/
    - ./media:/media/
    - ./log:/log
    networks:
      net:
        ipv4_address: 192.168.243.12

# -------------------------------------

  favorites:
    build:
      context: .
      dockerfile: services-dockerfile
    restart: always
    links:
      - postgres:postgres
    depends_on:
      - postgres
    environment: 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_ACTION}
    volumes:
    - ./build/user_action:/build/
    - ./log:/log
    networks:
      net:
        ipv4_address: 192.168.243.13

# -------------------------------------

  session:
    build:
      context: .
      dockerfile: services-dockerfile
    restart: always
    links:
      - redis:redis
    depends_on:
      - redis
    volumes:
    - ./build/session:/build/
    - ./log:/log
    networks:
      net:
        ipv4_address: 192.168.243.14

  payment:
    build:
      context: .
      dockerfile: services-dockerfile
    restart: always
    links:
      - user:user
    depends_on:
      - user
    environment: 
      - PAYMENT_SECRET=${PAYMENT_SECRET}
      - PAYMENT_SECRET2=${PAYMENT_SECRET2}
    volumes:
    - ./build/payment:/build/
    - ./log:/log
    networks:
      net:
        ipv4_address: 192.168.243.15

# -------------------------------------
# ========[ API-GATEWAY ]==============
# -------------------------------------

  api_gateway:
    build:
      context: .
      dockerfile: services-dockerfile
    restart: always
    ports:
      - 8080:80
    links:
      - session:session
      - user:user
      - favorites:favorites
      - content:content
      - payment:payment
    depends_on:
      - session
      - user
      - favorites
      - content
      - payment
    environment: 
      - CSRF_TOKEN=${CSRF_TOKEN}
    volumes:
    - ./build/api_gateway:/build/
    - ./log:/log
    networks:
      net:
        ipv4_address: 192.168.243.10


# -------------------------------------
# ===========[ VOLUMES ]===============
# -------------------------------------

volumes:
  redis-data:
  postgres-data:

        
# -------------------------------------
# ==========[ NETWORKS ]===============
# -------------------------------------


networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.243.0/24
