version: '3'


services:

# -------------------------------------
# ===========[ STORAGES ]==============
# -------------------------------------
  postgres:
    build:
      context: .
      dockerfile: postgres-dockerfile
    restart: always
    environment: 
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}  # from .env
    logging:
      options:
        max-size: 10m
        max-file: "3"
    # command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      net:
        ipv4_address: 192.168.243.20
        
# -------------------------------------

  redis:
    image: 'redis'
    restart: always
    volumes:
      - redis-data:/data
    networks:
      net:
        ipv4_address: 192.168.243.21
      
# -------------------------------------
# ==========[ SERVICES ]===============
# -------------------------------------

  content:
    build:
      context: .
      dockerfile: services-dockerfile
    restart: always
    links:
      - postgres:postgres
    depends_on:
      - postgres
    environment: 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
<<<<<<< HEAD
    - ./build_2023_05_23__20_02_03_3513bdea/content:/build/
=======
    - ./build_2023_05_22__04_26_45_a09baf4d/content:/build/
>>>>>>> 8489854e397065c7ac221b34e6a584ef2b280e9e
    - ./log:/log
    networks:
      net:
        ipv4_address: 192.168.243.11


# -------------------------------------

  user:
    build:
      context: .
      dockerfile: services-dockerfile
    restart: always
    links:
      - postgres:postgres
    depends_on:
      - postgres
    environment: 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
<<<<<<< HEAD
    - ./build_2023_05_23__20_02_03_3513bdea/user:/build/
=======
    - ./build_2023_05_22__04_26_45_a09baf4d/user:/build/
>>>>>>> 8489854e397065c7ac221b34e6a584ef2b280e9e
    - ./media:/media/
    - ./log:/log
    networks:
      net:
        ipv4_address: 192.168.243.12

# -------------------------------------

  favorites:
    build:
      context: .
      dockerfile: services-dockerfile
    restart: always
    links:
      - postgres:postgres
    depends_on:
      - postgres
    environment: 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
<<<<<<< HEAD
    - ./build_2023_05_23__20_02_03_3513bdea/user_action:/build/
=======
    - ./build_2023_05_22__04_26_45_a09baf4d/user_action:/build/
>>>>>>> 8489854e397065c7ac221b34e6a584ef2b280e9e
    - ./log:/log
    networks:
      net:
        ipv4_address: 192.168.243.13

# -------------------------------------

  session:
    build:
      context: .
      dockerfile: services-dockerfile
    restart: always
    links:
      - redis:redis
    depends_on:
      - redis
    volumes:
<<<<<<< HEAD
    - ./build_2023_05_23__20_02_03_3513bdea/session:/build/
=======
    - ./build_2023_05_22__04_26_45_a09baf4d/session:/build/
>>>>>>> 8489854e397065c7ac221b34e6a584ef2b280e9e
    - ./log:/log
    networks:
      net:
        ipv4_address: 192.168.243.14

  payment:
    build:
      context: .
      dockerfile: services-dockerfile
    restart: always
    links:
      - user:user
    depends_on:
      - user
    environment: 
      - PAYMENT_SECRET=${PAYMENT_SECRET}
      - PAYMENT_SECRET2=${PAYMENT_SECRET2}
    volumes:
<<<<<<< HEAD
    - ./build_2023_05_23__20_02_03_3513bdea/payment:/build/
=======
    - ./build_2023_05_22__04_26_45_a09baf4d/payment:/build/
>>>>>>> 8489854e397065c7ac221b34e6a584ef2b280e9e
    - ./log:/log
    networks:
      net:
        ipv4_address: 192.168.243.15

# -------------------------------------
# ========[ API-GATEWAY ]==============
# -------------------------------------

  api_gateway:
    build:
      context: .
      dockerfile: services-dockerfile
    restart: always
    ports:
      - 8080:80
    links:
      - session:session
      - user:user
      - favorites:favorites
      - content:content
      - payment:payment
    depends_on:
      - session
      - user
      - favorites
      - content
      - payment
    environment: 
      - CSRF_TOKEN=${CSRF_TOKEN}
    volumes:
<<<<<<< HEAD
    - ./build_2023_05_23__20_02_03_3513bdea/api_gateway:/build/
=======
    - ./build_2023_05_22__04_26_45_a09baf4d/api_gateway:/build/
>>>>>>> 8489854e397065c7ac221b34e6a584ef2b280e9e
    - ./log:/log
    networks:
      net:
        ipv4_address: 192.168.243.10


# -------------------------------------
# ===========[ VOLUMES ]===============
# -------------------------------------

volumes:
  redis-data:
  postgres-data:

        
# -------------------------------------
# ==========[ NETWORKS ]===============
# -------------------------------------


networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.243.0/24
