{
 "title": "Filmium",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "RPS Services",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (serivce) (rate(grpc_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency of services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (serivce) (increase(grpc_request_duration_seconds_historgram_sum[1m])) / sum by (serivce) (increase(grpc_request_duration_seconds_historgram_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum (rate(http_requests_total[1m])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "API Gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Requests per 10 min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{path!=\"/metrics\"}[10m])) by (path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taffic (RPS) of Paths",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{path!=\"/metrics\"}[1m])) by (path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (path) (rate(http_request_duration_seconds_historgram_sum{path!=\"/metrics\"}[1m])) / sum by (path) (rate(http_request_duration_seconds_historgram_count{path!=\"/metrics\"}[1m])) \r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{dfg!=\"/metrics\", status=~\"4.+|5.+\"}[1m])) / sum(increase(http_requests_total{dfg!=\"/metrics\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors / Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{dfg!=\"/metrics\", status=~\"4.+|5.+\"}[1m])) by (path, status)",
     "legendFormat": "{{status}} {{path}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  }
 ]
}