is_debug: true
server:
  port: 8082
postgres:
  # password from env
  user: postgres
  dbname: postgres
  host: 127.0.0.1
  port: 5432
  sslmode: disable
  search_path: user_schema
logging:
  dir: log
  filename: all.log.json
  levels: 
    - all
  project_dir: 2023_1_ContentDealers/user 
