name: Go

on:
  push:
    branches: [ "movie-selection-endpoint_FILM-6" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.4.0

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build cmd/main.go

    - name: Test
      run: |
        go test -cover -coverpkg ./... ./... -coverprofile=coverage.out
        go tool cover -func=coverage.out
        go tool cover -html=./coverage.out -o coverage.html
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: coverage.html
        path: coverage.html
