name: Go

on:
  push:
    branches: [ "deploy_FILM-20" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: make -B build 

    - name: Upload build result
      uses: actions/upload-artifact@v1
      with:
        name: build_dir
        path: ./build_0_*

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download build dir
        uses: actions/download-artifact@v1
        with:
          name: build_dir

      - name: Version increment on server
        uses: appleboy/ssh-action@master
        with:
          envs: GITHUB_SHA
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: cd filmium-new && make increment_versions && make update_docker_compose_volumes

      - name: Transfer build dir to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "build_dir"
          target: "/home/ubuntu/filmium-new/back"

      - name: Run new version app
        uses: appleboy/ssh-action@master
        with:
          envs: GITHUB_SHA
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: cd filmium-new && sudo docker compose restart

