global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'api_gateway'
    static_configs:
      - targets:
        - api_gateway:80

  # - job_name: 'system'
  #   static_configs:
  #     - targets: ['docker.for.mac.localhost:9100']

